### PR TITLE
chore(demo): use-gatsby-plugin-image

### PR DESCRIPTION
**Pull request by PaulieScanlon**
- update deps to use `gatsby-plugin-image`
- update `graphql` query in `Product.js`
- update to use `GatsbyImage` in `Products.js`
- Add additional snippet to `README.md`
- Add `.env.development` & `.env.production` to `.gitignore`

### CODE REVIEW

**Comment by notrab** [comment]
Thanks for the PR @PaulieScanlon 🙌🏻 ❤️ 

Will review + merge today

**Comment by PaulieScanlon** [comment]
@notrab Lovely stuff! Ty for the quick turn around. FYI i'm trying to help this chap out on Twitter: https://twitter.com/SamuelWanjare/status/1409743642311417857?s=20 

I'm not 100% sure he's referring to the plugin or commerce.js at all but... in case he is then this PR will help.

**Comment by notrab** [comment]
@PaulieScanlon nice one - above and beyond my man 🤩

**Comment by PaulieScanlon** [comment]
It's nice to nice ay! 🕺

**Review by notrab — APPROVED** [review]
LGTM 🥳 

Added `gatsby-plugin-image` to `gatsby-config.js` and cleaned up a remnant `}`.

**Comment by PaulieScanlon** [comment]
@notrab Doh! nice catch on `gatsby-config` 🤦

**Pull request merged**
